### ISSUE TITLE
Change the background color of selected text to an accent color

### ISSUE THREAD

**Issue by Phixyn** [Phixyn/no-bs-looper#72]
**Description**

Change background color of selected text (see Twitch.tv, including chat, for example).

This can be done using the [`::selection` CSS selector](https://www.w3schools.com/cssref/sel_selection.asp):

```css
::-moz-selection {
  background-color: var(--primary-background-color);
}

::selection {
  background-color: var(--primary-background-color);
}
```

So far, I've tried using the accent colors, but they don't really look good because of the contrast between the background and text color. We will need a new shade of accent color for this. See an example from Twitch chat selected text (it works on the whole site too):

![image](https://user-images.githubusercontent.com/9574132/95030419-88d68f80-06a7-11eb-843e-af28b9ee7036.png)
